apiVersion: v1
kind: Service
metadata:
  name: csvtojson-service
  labels:
    app: csvtojson-service
spec:
  type: LoadBalancer
  externalIPs:
  ports:
  - name: http
    port: 5000
    protocol: TCP
    targetPort: 5000
  selector:
    app: csvtojson
  sessionAffinity: None
