apiVersion: apps/v1
kind: Deployment
metadata:
  name: csvtojson-deployment
  labels:
    app: csvtojson
spec:
  replicas: 3
  selector:
    matchLabels:
      app: csvtojson
  template:
    metadata:
      labels:
        app: csvtojson
    spec:
      containers:
      - name: csvtojson
        image: paolomedallon/devopspao_csvtojson:1.0
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
